Fix pointcloud
stactools-packages/pointcloud pull request #3
Opened 2023-08-25 03:24 UTC by thomas-maschler

2023-08-25 12:20 UTC, gadomski requested changes

2023-08-25 12:20 UTC, gadomski commented on setup.cfg
>      Programming Language :: Python :: 3.7
```suggestion
```

[Python 3.7 is end-of-life](https://devguide.python.org/versions/) so we should remove it -- **stactools** is >= 3.8.

2023-08-25 12:20 UTC, gadomski commented on setup.cfg
>      stactools ~= 0.1
Should probably bump **stactools** as well, this is a really old version.

2023-08-25 12:20 UTC, gadomski commented on src/stactools/pointcloud/stac.py
> +    # from PDAL-python without reading the whole ˚file.
What's this change all about?

2023-08-25 13:28 UTC, gadomski requested changes

2023-08-25 13:28 UTC, gadomski commented on .github/workflows/continuous-integration.yml
> +        python-version: [3.8, 3.9, 3.10, 3.11]
I _think_ this will need quotes.
```suggestion
        python-version: ["3.8", "3.9", "3.10", "3.11"]
```

2023-08-25 13:28 UTC, gadomski approved these changes

2023-08-25 13:30 UTC, thomas-maschler commented
@gadomski the test suite is broken, the package seems to be missing some files. Do you want me to rewrite them?

2023-08-26 14:19 UTC, gadomski commented
Hm, I didn't see any missing files, but the spatial reference of the last file no longer has an EPSG 🤷🏼. I've removed that check and cleaned up one or two other things.

2023-08-28 12:35 UTC, merged